# Generated by Django 6.0.1 on 2026-02-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deebai', '0006_alter_conversationmessage_categories_searched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='categories_searched',
            field=models.CharField(blank=True, help_text="Categories searched (e.g., 'government,tourism')", max_length=200),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='chunks_retrieved',
            field=models.IntegerField(default=0, help_text='Number of RAG chunks retrieved'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='context_topics',
            field=models.TextField(blank=True, help_text='AI-generated summary of topics discussed'),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='session_key',
            field=models.CharField(help_text='Django session key', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of text chunks created from this document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the document was last processed', null=True),
        ),
    ]
