# Generated by Django 6.0.1 on 2026-01-24 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of text chunks created from this document'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the document content'),
        ),
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False, help_text='Whether this document has been processed and added to ChromaDB'),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the document was last processed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('government', 'Government'), ('biography', 'Biography'), ('programs', 'Programs'), ('projects', 'Projects'), ('tourism', 'Tourism'), ('events', 'Events'), ('history', 'History'), ('announcements', 'Announcements')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Supported formats: PDF, DOCX, TXT', upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])]),
        ),
    ]
