# Generated by Django 6.0.1 on 2026-01-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0002_alter_document_options_document_chunk_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('government', 'Government'), ('biography', 'Biography'), ('programs', 'Programs'), ('projects', 'Projects'), ('tourism', 'Tourism'), ('events', 'Events'), ('history', 'History'), ('announcements', 'Announcements')], max_length=50),
        ),
    ]
