# Generated by Django 6.0.1 on 2026-01-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0004_conversationsession_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('government', 'Government'), ('biography', 'Biography'), ('programs', 'Programs'), ('projects', 'Projects'), ('tourism', 'Tourism'), ('events', 'Events'), ('history', 'History'), ('announcements', 'Announcements')], max_length=50),
        ),
    ]
