# Generated by Django 6.0.1 on 2026-02-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0005_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='categories_searched',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='chunks_retrieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='context_topics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='session_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
