# Generated by Django 6.0.1 on 2026-03-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0007_alter_conversationmessage_categories_searched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, default='n/a', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('validated_at', models.CharField(blank=True, max_length=100)),
                ('validated_by', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('user_retention', models.CharField(blank=True, max_length=200)),
                ('office_retention', models.CharField(blank=True, max_length=200)),
                ('overall_days_onprocess', models.CharField(blank=True, max_length=200)),
                ('document_completed_status', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tracked Document',
                'verbose_name_plural': 'Tracked Documents',
                'ordering': ['-updated_timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='categories_searched',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='chunks_retrieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='context_topics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='session_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
