# Generated by Django 6.0.1 on 2026-03-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0008_trackeddocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackeddocument',
            name='id',
        ),
        migrations.AddField(
            model_name='trackeddocument',
            name='pdid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
